# Reference: https://squidfunk.github.io/mkdocs-material/reference/
site_name: SANS Holiday Hack Challenge 2025 Write-Up
site_author: Ashish Gupta
site_description: Write-Up for SANS Holiday Hack Challenge 2025 
theme:
  icon:
    # Material for MkDocs bundles several icon sets:
    # - Material Design (https://materialdesignicons.com/)
    # - FontAwesome (https://fontawesome.com/search?m=free)
    # - Octicons (https://octicons.github.com/)
    # - Simple Icons (https://simpleicons.org/)
    # Below are some suitable logo examples: 
    # logo: fontawesome/regular/snowflake
    # logo: fontawesome/solid/sleigh
    # logo: fontawesome/solid/candy-cane
    logo: fontawesome/solid/tree
  name: material
  favicon: img/misc/favicon.ico
  features:
    - toc.integrate
    - content.code.copy
    - navigation.sections
    #- navigation.instant
    #- navigation.top
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.expand
    #- navigation.top
    #- navigation.prune
    #- toc.follow
  palette:
    # Material for MkDocs supports a light (default) and dark (slate) theme.
    # Each mode supports configurable primary and accent colors.
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    # Primary colors:
    # red, pink, purple, deep purple, indigo, blue, light blue, cyan, teal,
    # green, light green, lime, yellow, amber, orange, deep orange, brown,
    # grey, blue grey, black, and white.
    # Accent colors:
    # red, pink, purple, deep purple, indigo, blue, light blue, cyan, teal,
    # green, light green, lime, yellow, amber, orange, and deep orange.
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/<twitter_username>
      name: Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/<github_username>
      name: GitHub
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/<instagram_username>
      name: Instagram
extra_css:
  - css/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - js/tablesort.js
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - meta
  - footnotes
  - def_list
  - toc:
      permalink: ⚓︎
      toc_depth: 2
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
# The 'nav' section defines the content of the sidebar navigation.
- Welcome: 'index.md'
- Objectives:
  - Act 1:
    - Holiday Hack Orientation: 'objectives/orientation.md'
    - Its All About Defang: 'objectives/Its_All_About_Defang.md'
    - Neighborhood Watch Bypass: 'objectives/Neighborhood_Watch_Bypass.md'
    - Santa Gift-Tracking Service Port Mystery: 'objectives/Santa_Gift-Tracking_Service_Port_Mystery.md'
    - Visual Networking Thinger: 'objectives/Visual_Networking_Thinger.md'
    - Visual Firewall Thinger: 'objectives/Visual_Firewall_Thinger.md'
    - Intro to Nmap: 'objectives/Intro_to_Nmap.md'
    - Blob Storage Challenge in the Neighborhood: 'objectives/Blob_Storage_Challenge_in_the_Neighborhood.md'
    - Spare Key: 'objectives/Spare_Key.md'
    - The Open Door: 'objectives/The_Open_Door.md'
    - Owner: 'objectives/Owner.md'
  - Act 2:
    - Retro Recovery: 'objectives/Retro_Recovery.md'
    - Mail Detective: 'objectives/Mail_Detective.md'
    - IDORable Bistro: 'objectives/IDORable_Bistro.md'
    - Dosis Network Down: 'objectives/Dosis_Network_Down.md'
    - Rogue Gnome Identity Provider: 'objectives/Rogue_Gnome_Identity_Provider.md'
    - Quantgnome Leap: 'objectives/Quantgnome_Leap.md'
    - Going in Reverse: 'objectives/Going_in_Reverse.md'
  - Act 3:
    - Gnome Tea: 'objectives/Gnome_Tea.md'
    - Hack-a-Gnome: 'objectives/Hack_a_Gnome.md'
    - Snowcat RCE & Priv-Esc: 'objectives/Snowcat-RCE-&-Priv-Esc.md'
    - Schrodingers Scope: 'objectives/Schrodingers_Scope.md'
    - Find and Shutdown Frostys Snowglobe Machine: 'objectives/Find-and-Shutdown-Frostys-Snowglobe-Machine.md'
    - On the Wire: 'objectives/On-the-Wire.md'
    - Free Ski: 'objectives/Free_Ski.md'
    - Snowblind ambush: 'objectives/snowblind_ambush.md'
